import AboutDialog from './about-dialog.jsx';
import MemberProfileDialog from './member-profile-dialog.jsx';
import About from './about.jsx';
import MemberProfile from './member-profile.jsx';
import BuildInfo from './build-info.jsx';
import Routes from './routes.js';
import DraftEditor from './draft-editor.jsx';
import StatusDot from './status-dot.jsx';
import EmojiPopover from './emoji-popover.jsx';
import UserAvatar from './user-avatar.jsx';
import UserChangePasswordDialog from './user-change-password-dialog.jsx';
import FileListItem from './file-list-item.jsx';
import UserListItem from './user-list-item.jsx';
import FileListView from './file-list.jsx';
import UserProfileDialog from './user-profile-dialog.js';
import HotkeySettingDialog from './hotkey-setting-dialog.jsx';
import UserSettingDialog from './user-setting-dialog.jsx';
import MemberListItem from './member-list-item.jsx';
import UserSetting from './user-setting.jsx';
import MemberList from './member-list.jsx';
import withReplaceView from '../with-replace-view.js';

export default {
    get AboutDialog() {return withReplaceView(AboutDialog);},
    get MemberProfileDialog() {return withReplaceView(MemberProfileDialog);},
    get About() {return withReplaceView(About);},
    get MemberProfile() {return withReplaceView(MemberProfile);},
    get BuildInfo() {return withReplaceView(BuildInfo);},
    get Routes() {return withReplaceView(Routes);},
    get DraftEditor() {return withReplaceView(DraftEditor);},
    get StatusDot() {return withReplaceView(StatusDot);},
    get EmojiPopover() {return withReplaceView(EmojiPopover);},
    get UserAvatar() {return withReplaceView(UserAvatar);},
    get UserChangePasswordDialog() {return withReplaceView(UserChangePasswordDialog);},
    get FileListItem() {return withReplaceView(FileListItem);},
    get UserListItem() {return withReplaceView(UserListItem);},
    get FileListView() {return withReplaceView(FileListView);},
    get UserProfileDialog() {return withReplaceView(UserProfileDialog);},
    get HotkeySettingDialog() {return withReplaceView(HotkeySettingDialog);},
    get UserSettingDialog() {return withReplaceView(UserSettingDialog);},
    get MemberListItem() {return withReplaceView(MemberListItem);},
    get UserSetting() {return withReplaceView(UserSetting);},
    get MemberList() {return withReplaceView(MemberList);},
};
